# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://derekwayne.github.io
title: Wayne Analytics 
email: derekwayne4@gmail.com 
author: Derek Wayne 
description: Derek Wayne's Data Science and Machine Learning Project Portfolio
copyright: 'Copyright &copy; 2019 Derek Wayne. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

plugins:
        - jekyll-seo-tag

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
# Google Analytics
google_analytics: UAâ€”138576131-1

social:
  - title: twitter
    url: 
  - title: github
    url: https://github.com/derekwayne
  - title: linkedin
    url: https://www.linkedin.com/in/derek-wayne/ 
